### ISSUE TITLE
'RegistrationFormPersonalDataSection' object has no attribute 'active_fields'

### ISSUE THREAD

**Issue by jouvin** [bpedersen2/indico-mlz-export#14]
Hi,

I updated our Indico instance to 3.3 and at the same time updated mlzexport to last master, 2.32 according to the log:

```
commit 593d1a34a3abf7dbee55805defd787aea6e02dc9 (HEAD, upstream/master, upstream/HEAD)
Merge: 97d6e51 c8da5d6
Author: Björn Pedersen <bjoern.pedersen@frm2.tum.de>
Date:   Tue May 21 10:59:41 2024 +0200

    Merge pull request #12 from bpedersen2/dependabot/pip/api_example/requests-2.32.0

    Bump requests from 2.31.0 to 2.32.0 in /api_example
```

but `3.2.dev23` according to pip list.

Since then, I have the following exception when trying to acces registration data:

```
Traceback (most recent call last):
  File "/opt/indico/.venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/flask_pluginengine/util.py", line 190, in wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/indico/web/flask/util.py", line 80, in wrapper
    return obj().process()
           ^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/indico/web/rh.py", line 307, in process
    res = self._do_process()
          ^^^^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/indico/web/rh.py", line 275, in _do_process
    rv = self._process()
         ^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/indico/web/rh.py", line 213, in _process
    return method()
           ^^^^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/indico_mlz_export/controller.py", line 61, in _process_GET
    return jsonify(all_registrations(self.event, self.FLAT))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/indico_mlz_export/api.py", line 104, in all_registrations
    result.append(process_field_data(_registration, flat))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/indico_mlz_export/api.py", line 184, in process_field_data
    one_res['data'] = all_fields(_registration, flat)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/indico/.venv/lib/python3.12/site-packages/indico_mlz_export/api.py", line 199, in all_fields
    for field in section.active_fields:
                 ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RegistrationFormPersonalDataSection' object has no attribute 'active_fields'
```

Is it a known issue? Is there a trivial workaround? It is a bad timing as it is the holiday period but the people depending on mlzexport seems not to be in holidays...

Thanks in advance for your help.

Michel

**Comment by bpedersen2** [comment]
Good question, as we use this only infrequently I did not yet observer these errors. But I'll take a look at the changes in 3.3 to find out if this needs code changes ( it may take a day or 2)

**Comment by jouvin** [comment]
The fix is trivial: `active_fields` has been renamed `available_fields` (thanks to Adrian for providing the information). I already implemented the fix and Adrian told me he will submit a PR!

**Comment by ThiefMaster** [comment]
Just wondering: Do you care about compatibility w/ older Indico versions? I would just bump the requirement to `indico>=3.3.3` and thus avoid the need to fall back to the old name..

**Comment by bpedersen2** [comment]
No,  the plugin does not need backwards compat, older version are availaible via appropriate tags.
