### ISSUE TITLE
Indico  v3.1

### ISSUE THREAD

**Issue by FredH-ITER** [bpedersen2/indico-mlz-export#7]
Hello,

is the plugin working with last indico 3.1 version ?

> bash-4.2$ mkdir -p /tmp/dev/dist
bash-4.2$ mkdir /tmp/git; cd /tmp/git
bash-4.2$ git clone https://github.com/bpedersen2/indico-mlz-export.git
bash-4.2$ git clone https://github.com/indico/indico.git
bash-4.2$ source /opt/indico/.venv/bin/activate
(indico) -bash-4.2$ /tmp/git/indico/bin/maintenance/build-wheel.py -d /tmp/dev/dist plugin /tmp/git/indico-mlz-export/
plugin has no assets
plugin has no translations
cleaning build dirs
building wheel
cleaning build dirs
(indico) -bash-4.2$ cd /tmp/dev/dist/
(indico) -bash-4.2$ pip install indico_mlz_export-2.3.2.dev6+gebe8dc1-py3-none-any.whl
[...]
Requirement already satisfied: setuptools in /opt/indico/.venv/lib/python3.9/site-packages (from celery[redis]==5.2.2->indico>=2.3.0->indico-mlz-export==2.3.2.dev6+gebe8dc1) (60.5.0)
Installing collected packages: indico-mlz-export
Successfully installed indico-mlz-export-2.3.2.dev6+gebe8dc1

> (indico) -bash-4.2$ indico setup list-plugins
Traceback (most recent call last):
  File "/opt/indico/.venv/bin/indico", line 8, in <module>
    sys.exit(cli())
  File "/opt/indico/.venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/indico/.venv/lib/python3.9/site-packages/flask/cli.py", line 600, in main
    return super().main(*args, **kwargs)
  File "/opt/indico/.venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/indico/.venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/cli/util.py", line 108, in invoke
    return self._impl.invoke(ctx)
  File "/opt/indico/.venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/indico/.venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/indico/.venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico/cli/setup.py", line 185, in list_plugins
    plugin = ep.load()
  File "/opt/indico/.venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2465, in load
    return self.resolve()
  File "/opt/indico/.venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2471, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico_mlz_export/plugin.py", line 31, in <module>
    from indico_mlz_export.blueprint import blueprint
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico_mlz_export/blueprint.py", line 31, in <module>
    from indico_mlz_export.controller import RHExportRegistrations, RHExportRegistration, RHExportRegistrationsFlat, RHExportRegistrationFlat
  File "/opt/indico/.venv/lib/python3.9/site-packages/indico_mlz_export/controller.py", line 33, in <module>
    from indico.modules.oauth import oauth
ImportError: cannot import name 'oauth' from 'indico.modules.oauth' (/opt/indico/.venv/lib/python3.9/site-packages/indico/modules/oauth/__init__.py)

Thanks for your advice.

**Comment by bpedersen2** [comment]
Not yet, update is coming in a few days

**Comment by bpedersen2** [comment]
v3.1 should be compatible with indico 3.1

**Comment by FredH-ITER** [comment]
Nice ! seems to work, fast & good job.
just declaration name to change in indico.conf   now 'mlz_export'    _(before was 'mlzexport')_
